apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
      - name: mern-server
        image: bennz03/mern-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/merndb"
